In case you need a &+c;key&-c; to resolve to a blank &+c;value&-c;, set &+c; @ &-c; as the value.

---

&+C;# define SAMPLE
// Flush streams to file and close it
int tmperr = fclose(file_ptr);
if (tmperr != 0) {
	PRINT_SYSTEM_ERROR("fclose", "Failed to close the output file.");
	return -1;
}
&-C;
---

&+C;Å = 0xC5                ; for an encoding file&-C;
&+C;F_BOLD_OFF = 0x1B 0x45  ; for a printer feature file&-C;
&+C;F_H3_ON = @             ; ditto&-C;

---

Symbols in code blocks &+c;should *not* # be __converted__&-c;.

&+C;This **shouldn't work**.
## This shouldn't work.
> This shouldn't work.
<This shouldn't work>.

***

The horizontal rule should stay there.
&-C;